export interface CountryData {
  name: string;
  code: string;
  flag: string;
  dialCode: string;
}

export const countries: CountryData[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', dialCode: '+93' },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', dialCode: '+355' },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', dialCode: '+213' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', dialCode: '+54' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', dialCode: '+61' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', dialCode: '+43' },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', dialCode: '+973' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', dialCode: '+880' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', dialCode: '+32' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', dialCode: '+55' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', dialCode: '+1' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', dialCode: '+56' },
  { name: 'China', code: 'CN', flag: '🇨🇳', dialCode: '+86' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', dialCode: '+57' },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', dialCode: '+385' },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', dialCode: '+357' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿', dialCode: '+420' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', dialCode: '+45' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', dialCode: '+20' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', dialCode: '+358' },
  { name: 'France', code: 'FR', flag: '🇫🇷', dialCode: '+33' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', dialCode: '+49' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', dialCode: '+30' },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', dialCode: '+852' },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', dialCode: '+36' },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', dialCode: '+354' },
  { name: 'India', code: 'IN', flag: '🇮🇳', dialCode: '+91' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', dialCode: '+62' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', dialCode: '+98' },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', dialCode: '+964' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', dialCode: '+353' },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', dialCode: '+972' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', dialCode: '+39' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', dialCode: '+81' },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', dialCode: '+962' },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', dialCode: '+965' },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', dialCode: '+961' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', dialCode: '+60' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', dialCode: '+52' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', dialCode: '+212' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱', dialCode: '+31' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', dialCode: '+64' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', dialCode: '+47' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', dialCode: '+968' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', dialCode: '+92' },
  { name: 'Palestine', code: 'PS', flag: '🇵🇸', dialCode: '+970' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', dialCode: '+63' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', dialCode: '+48' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '+351' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', dialCode: '+974' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', dialCode: '+40' },
  { name: 'Russia', code: 'RU', flag: '🇷🇺', dialCode: '+7' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', dialCode: '+966' },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', dialCode: '+381' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', dialCode: '+65' },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', dialCode: '+421' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', dialCode: '+27' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷', dialCode: '+82' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', dialCode: '+34' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '+94' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', dialCode: '+46' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', dialCode: '+41' },
  { name: 'Syria', code: 'SY', flag: '🇸🇾', dialCode: '+963' },
  { name: 'Taiwan', code: 'TW', flag: '🇹🇼', dialCode: '+886' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', dialCode: '+66' },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', dialCode: '+216' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷', dialCode: '+90' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', dialCode: '+380' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', dialCode: '+971' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', dialCode: '+44' },
  { name: 'United States', code: 'US', flag: '🇺🇸', dialCode: '+1' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳', dialCode: '+84' },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', dialCode: '+967' },
];
